name: Run Postman Collection

on:
  push:
    branches: [ msc ]
  workflow_dispatch: {}

jobs:
  run-postman-collection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Postman login
        env:
          POSTMAN_KEY: ${{ secrets.POSTMAN_KEY }}
        run: |
          set -euo pipefail
          postman login --with-api-key "$POSTMAN_KEY"

      - name: Run Postman collection
        run: |
          set -euo pipefail
          postman collection run 53180818-ee8ad1ac-8e16-41b4-8412-656df1e79daa -e 53180818-f617756c-9ee9-4240-b856-2ff529a6928c
