name: Run Postman Collection

on:
  workflow_dispatch:
  push:
    branches: [ msc ]

jobs:
  postman-run:
    name: Login and run Postman collection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Postman CLI
        run: npm install -g @postman/postman-cli

      - name: Postman login
        env:
          POSTMAN_KEY: ${{ secrets.POSTMAN_KEY }}
        run: |
          postman login --with-api-key $POSTMAN_KEY

      - name: Run collection
        run: |
          postman collection run 53180818-ee8ad1ac-8e16-41b4-8412-656df1e79daa -e 53180818-f617756c-9ee9-4240-b856-2ff529a6928c
